AUTOMATIC_MODE = "Automatic Segmentation"
BOX_PROMPT_MODE = "Box Prompt"
PIXELIZE_FILTER = "Pixelize"
COLOR_FILTER = "Solid Color"
SOUND_FILE_EXT = ['.mp3', '.wav', '.aac', '.flac', '.ogg', '.m4a', '.wma']
IMAGE_FILE_EXT = ['.jpg', '.jpeg', '.png', '.gif', '.bmp', '.tiff', '.webp']
VIDEO_FILE_EXT = ['.mp4', '.avi', '.mov', '.wmv', '.flv', '.webm', '.mkv', '.mpeg', '.mpg', '.m4v', '.3gp', '.ts', '.vob']
DEFAULT_COLOR = "#00FF00"
DEFAULT_PIXEL_SIZE = 8